# Setup
title: tcps
tagline: 
url: https://ttcps.github.io
baseurl: ""
permalink: /:title/
timezone: Asia/Shanghai

version: "10A3"
previewcode: 'abc'

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
ga_analytics: 

# Specify the author for blog posts
author:
  name: tcps
  url: https://ttcps.github.io/
  email: tcps0team@gmail.com
